### PR TITLE
Qald9 10 links

### PR DESCRIPTION
**Pull request by janreineke**
Fixed broken link to QALD9 website and added link to QALD10.

### CODE REVIEW

**Comment by RicardoUsbeck** [comment]
Thanks for the pull request. Could you look into why this error happens 
image

I think people's complaint was about the https error the first time you open the webpage where for example in Chrome you got to say: Yes, proceed to website

**Comment by xixi019** [comment]
It seems to be a problem with the website domain, we might need to buy a certificate to fix that issue.

**Comment by RicardoUsbeck** [comment]
There is letsencrypt which is for free

**Comment by RicardoUsbeck** [comment]
Do you think the browser can be solved in this repo or shall we move the issue itself somewhere else, e.g. to a slack discussion? (For me, the error persists)

**Comment by RicardoUsbeck** [comment]
I think we can merge this one and resolve the certificate issue offtopic

**Pull request merged**
